'use strict';function updateProps(){var pc=document.getElementById('ppc');if(!pc)return;
var _focId=null,_focSS=0,_focSE=0;var _af=document.activeElement;if(_af&&pc.contains(_af)&&_af.id){_focId=_af.id;_focSS=_af.selectionStart||0;_focSE=_af.selectionEnd||0;}
if(!selIds.size){pc.innerHTML='<div style="text-align:center;padding:16px;color:var(--text3)"><i class="fas fa-hand-pointer" style="font-size:20px;opacity:0.3;display:block;margin-bottom:6px"></i><p style="font-size:11px"></p></div>';pc.querySelector('p').textContent=t('select_hint');return;}
var h='',el=null;selIds.forEach(function(id){if(!el)el=els.find(function(e){return e.id===id;});});if(!el)return;
var isP=isP2D(el.type),isA=isArr(el.type),isF=isFree(el.type);
h+='<div class="prop-group"><div class="prop-label">'+t('color')+'</div>';
// Color palette presets
h+='<div class="color-grid">';
['#e84040','#4a90d9','#50c878','#f0c040','#ff6b2b','#c070f0','#40c0e8','#ffffff','#e8960c','#ff69b4','#00e5ff','#8b5cf6','#ec4899','#14b8a6','#f97316','#64748b'].forEach(function(c){h+='<div class="color-dot'+(el.color===c?' on':'')+'" style="background:'+c+'" onclick="sp(\'color\',\''+c+'\')"></div>';});
h+='</div>';
// Custom color picker
h+='<div style="display:flex;gap:4px;align-items:center;margin-top:6px">';
h+='<input type="color" value="'+(el.color||'#ffffff')+'" onchange="sp(\'color\',this.value)" style="width:36px;height:28px;border:none;cursor:pointer;border-radius:4px">';
h+='<button class="angle-btn" onclick="addFavColor(\''+(el.color||'#ffffff')+'\')" style="flex:1;font-size:9px"><i class="fas fa-star" style="color:var(--warning)"></i> '+(lang==='ar'?'\u0625\u0636\u0627\u0641\u0629':'Add')+'</button>';
h+='</div>';
// Favorite colors
if(favoriteColors.length>0){
h+='<div class="prop-label" style="margin-top:6px"><i class="fas fa-star" style="color:var(--warning);font-size:9px"></i> '+(lang==='ar'?'\u0627\u0644\u0645\u0641\u0636\u0644\u0629':'Favorites')+'</div>';
h+='<div class="cp-fav-row">';
favoriteColors.forEach(function(c){h+='<div class="cp-fav" style="background:'+c+'" onclick="sp(\'color\',\''+c+'\')" title="'+c+'"><span class="cp-fav-x" onclick="event.stopPropagation();removeFavColor(\''+c+'\')">&times;</span></div>';});
h+='</div>';}
h+='</div>';
if(isZone(el.type)){var _zw=el.zoneW||(el.size||18)*2.4,_zh=el.zoneH||(el.size||18)*1.6;h+='<div class="prop-group"><div class="prop-label">'+(lang==='ar'?'العرض':'Width')+' <span class="prop-val">'+Math.round(_zw)+'</span></div><input type="number" value="'+Math.round(_zw)+'" oninput="sp(\'zoneW\',+this.value)"></div>';h+='<div class="prop-group"><div class="prop-label">'+(lang==='ar'?'الارتفاع':'Height')+' <span class="prop-val">'+Math.round(_zh)+'</span></div><input type="number" value="'+Math.round(_zh)+'" oninput="sp(\'zoneH\',+this.value)"></div>';}else{var _szMax=isZone(el.type)?1000:80;h+='<div class="prop-group"><div class="prop-label">'+t('size')+' <span class="prop-val">'+(el.size||18)+'</span></div><input type="range" min="6" max="'+_szMax+'" value="'+(el.size||18)+'" oninput="sp(\'size\',+this.value)"></div>';}
if(!isF&&el.type!=='smallGoal'){h+='<div class="prop-group"><div class="prop-label">'+t('rotation')+' <span class="prop-val">'+(el.rotation||0)+'°</span></div><input type="range" min="0" max="360" value="'+(el.rotation||0)+'" oninput="sp(\'rotation\',+this.value)"></div>';}
h+='<div class="prop-group"><div class="prop-label">'+t('opacity')+' <span class="prop-val">'+Math.round((el.opacity!==undefined?el.opacity:1)*100)+'%</span></div><input type="range" min="10" max="100" value="'+Math.round((el.opacity!==undefined?el.opacity:1)*100)+'" oninput="sp(\'opacity\',this.value/100)"></div>';
if(el.type==='smallGoal')h+='<div class="prop-group"><div class="prop-label">'+(lang==='ar'?'الظل':'Shadow')+'</div><div style="display:flex;gap:3px"><button class="angle-btn'+(el.castShadow!==false?' on':'')+'" onclick="sp(\'castShadow\',el.castShadow===false?true:false)"><i class="fas fa-shadow"></i> '+(lang==='ar'?'مفعّل':'On')+'</button></div></div>';
if(el.type==='text'||el.type==='number'){h+='<div class="prop-group"><div class="prop-label">'+t('content')+'</div><input id="_txtCont" class="prop-input" oninput="sp(\'text\',this.value)"></div><div class="prop-group"><div class="prop-label">'+t('font_size')+' <span class="prop-val">'+(el.fontSize||18)+'</span></div><input type="range" min="8" max="72" value="'+(el.fontSize||18)+'" oninput="sp(\'fontSize\',+this.value)"></div><div class="prop-group"><div class="prop-label">'+t('color')+'</div><input type="color" value="'+(el.color||'#ffffff')+'" onchange="sp(\'color\',this.value)" style="width:100%;height:24px;border:none;cursor:pointer"></div><div class="prop-group"><div class="prop-label">'+t('bg_color')+'</div><div style="display:flex;gap:4px;align-items:center"><input type="color" value="'+(el.bgColor||'#000000')+'" onchange="sp(\'bgColor\',this.value||null)" style="width:36px;height:24px;border:none;cursor:pointer;flex-shrink:0"><button class="angle-btn" onclick="sp(\'bgColor\',null)" style="flex-shrink:0">'+(lang==='ar'?'لا شيء':'None')+'</button></div></div><div class="prop-group"><div class="prop-label">'+t('border')+'</div><div style="display:flex;gap:4px;align-items:center"><button class="angle-btn'+(el.borderColor?' on':'')+'" onclick="sp(\'borderColor\',el.borderColor?null:el.color||\'#ffffff\')">'+(lang==='ar'?'تفعيل':'Toggle')+'</button>'+(el.borderColor?'<input type="color" value="'+el.borderColor+'" onchange="sp(\'borderColor\',this.value)" style="width:36px;height:24px;border:none;cursor:pointer;flex-shrink:0">':'')+'</div></div><div class="prop-group"><div class="prop-label">'+t('font_family')+'</div><select onchange="sp(\'fontFamily\',this.value)" style="width:100%;padding:4px;border-radius:var(--radius-sm);background:var(--bg2);color:var(--text);border:1px solid var(--border);font-size:11px"><option value="Cairo,Inter" '+(el.fontFamily==='Cairo,Inter'?'selected':'')+'>Cairo</option><option value="Inter,Cairo" '+(el.fontFamily==='Inter,Cairo'?'selected':'')+'>Inter</option><option value="Arial,sans-serif" '+(el.fontFamily==='Arial,sans-serif'?'selected':'')+'>Arial</option><option value="\'Courier New\',monospace" '+(el.fontFamily==="'Courier New',monospace"?'selected':'')+'>Courier New</option><option value="Georgia,serif" '+(el.fontFamily==='Georgia,serif'?'selected':'')+'>Georgia</option><option value="Tahoma,sans-serif" '+(el.fontFamily==='Tahoma,sans-serif'?'selected':'')+'>Tahoma</option></select></div><div class="prop-group"><div style="display:flex;gap:4px"><button class="angle-btn'+(el.bold!==false?' on':'')+'" onclick="sp(\'bold\',el.bold===false?true:false)"><b>B</b></button><button class="angle-btn'+(el.italic?' on':'')+'" onclick="sp(\'italic\',!el.italic)"><i>I</i></button></div></div>';}
  if(isA){h+='<div class="prop-group"><div class="prop-label">'+t('thickness')+' <span class="prop-val">'+(el.size||2.5)+'</span></div><input type="range" min="1" max="10" step="0.5" value="'+(el.size||2.5)+'" oninput="sp(\'size\',+this.value)"></div>';if(el.type==='arrowCurved'){var _cv=el.curve!==undefined?el.curve:40;h+='<div class="prop-group"><div class="prop-label">'+t('curve')+' <span class="prop-val">'+_cv+'</span></div><input type="range" min="-100" max="100" value="'+_cv+'" oninput="sp(\'curve\',+this.value)"></div>';}if(el.type==='arrowSlalom'){h+='<div class="prop-group"><div class="prop-label">'+(lang==='ar'?'سعة التموج':'Amplitude')+' <span class="prop-val">'+(el.slalomAmp||15)+'</span></div><input type="range" min="2" max="50" value="'+(el.slalomAmp||15)+'" oninput="sp(\'slalomAmp\',+this.value)"></div>';h+='<div class="prop-group"><div class="prop-label">'+(lang==='ar'?'التردد':'Frequency')+' <span class="prop-val">'+(el.slalomFreq||2)+'</span></div><input type="range" min="0.5" max="6" step="0.5" value="'+(el.slalomFreq||2)+'" oninput="sp(\'slalomFreq\',+this.value)"></div>';}}
if(isP){if(el.displayStyle==='jersey'||playerDisplayStyle==='jersey')h+='<div class="prop-group"><div class="prop-label">'+(lang==='ar'?'الالوان':'Colors')+'</div><div style="display:flex;gap:4px;align-items:center"><div style="display:flex;flex-direction:column;align-items:center;gap:1px"><input type="color" value="'+(el.color||'#4a90d9')+'" onchange="sp(\'color\',this.value)" style="width:20px;height:20px;border-radius:3px;border:2px solid var(--border);cursor:pointer;padding:0"><span style="font-size:7px;color:var(--text3)">1</span></div><div style="display:flex;flex-direction:column;align-items:center;gap:1px"><input type="color" value="'+(el.jerseyColor2||'#ffffff')+'" onchange="sp(\'jerseyColor2\',this.value)" style="width:20px;height:20px;border-radius:3px;border:2px solid var(--border);cursor:pointer;padding:0"><span style="font-size:7px;color:var(--text3)">2</span></div></div></div>';h+='<div class="prop-group"><div class="prop-label"><i class="fas fa-id-badge" style="color:var(--accent);margin-inline-end:3px"></i>'+t('player_name')+'</div><input id="_pnName" class="prop-input" oninput="sp(\'playerName\',this.value)" placeholder="'+t('player_name_ph')+'"></div>';h+='<div class="prop-group"><div class="prop-label"><i class="fas fa-palette" style="margin-inline-end:3px"></i>'+(lang==='ar'?'\u0644\u0648\u0646 \u0627\u0644\u0627\u0633\u0645':'Name Color')+'</div><div style="display:flex;gap:4px;align-items:center"><input type="color" id="_pnColor" value="'+(el.nameColor||'#ffffff')+'" onchange="sp(\'nameColor\',this.value)" style="width:36px;height:26px;border:none;cursor:pointer"><button class="angle-btn" onclick="sp(\'nameColor\',null)" style="flex:1;font-size:9px"><i class="fas fa-undo"></i> '+(lang==='ar'?'\u0627\u0641\u062A\u0631\u0627\u0636\u064A':'Default')+'</button></div></div>';h+='<div class="prop-group"><div class="prop-label"><i class="fas fa-text-height" style="margin-inline-end:3px"></i>'+(lang==='ar'?'\u062D\u062C\u0645 \u062E\u0637 \u0627\u0644\u0627\u0633\u0645':'Name Size')+' <span class="prop-val">'+(el.nameSize||10)+'</span></div><input type="range" id="_pnSize" min="4" max="32" value="'+(el.nameSize||10)+'" oninput="sp(\'nameSize\',+this.value)"></div>';}
  if(isZone(el.type)){h+='<div class="prop-group"><div class="prop-label">'+t('color')+' 2</div><input type="color" value="'+(el.zoneColor2||'#ffffff')+'" onchange="sp(\'zoneColor2\',this.value)" style="width:100%;height:24px;border:none;cursor:pointer"></div>';if(el.type==='zoneRect2C'||el.type==='zoneCircle'||el.type==='zoneRect')h+='<div class="prop-group"><div class="prop-label">'+(lang==='ar'?'تكرار':'Repeat')+' <span class="prop-val">'+(el.zoneRepeat||1)+'</span></div><input type="range" min="1" max="10" value="'+(el.zoneRepeat||1)+'" oninput="sp(\'zoneRepeat\',+this.value)"></div>';h+='<div class="prop-group"><div class="prop-label">'+(lang==='ar'?'نوع الخط':'Line Style')+'</div><div style="display:flex;gap:3px"><button class="angle-btn'+(el.lineStyle!=='solid'?' on':'')+'" onclick="sp(\'lineStyle\',\'dashed\')">'+(lang==='ar'?'متقطع':'Dashed')+'</button><button class="angle-btn'+(el.lineStyle==='solid'?' on':'')+'" onclick="sp(\'lineStyle\',\'solid\')">'+(lang==='ar'?'متواصل':'Solid')+'</button></div></div>';h+='<div class="prop-group"><div class="prop-label">'+(lang==='ar'?'سماكة الخط':'Line Width')+' <span class="prop-val">'+(el.lineWidth||2)+'</span></div><input type="range" min="0.5" max="8" step="0.5" value="'+(el.lineWidth||2)+'" oninput="sp(\'lineWidth\',+this.value)"></div>';}
  if(el.type==='stick'){h+='<div class="prop-group"><div class="prop-label">'+t('color')+' 2 <span style="font-size:9px;color:var(--text3)">'+(lang==='ar'?'القاعدة':'Base')+'</span></div><input type="color" value="'+(el.stickBaseColor||'#333333')+'" onchange="sp(\'stickBaseColor\',this.value)" style="width:100%;height:24px;border:none;cursor:pointer"></div>';}
if(el.type==='reboundBoard'){h+='<div class="prop-group"><div class="prop-label">'+(lang==='ar'?'زاوية الإمالة':'Tilt Angle')+' <span class="prop-val">'+(el.reboundAngle||0)+'°</span></div><input type="range" min="-45" max="45" value="'+(el.reboundAngle||0)+'" oninput="sp(\'reboundAngle\',+this.value)"></div>';}
if(el.type==='smallGoal'){h+='<div class="prop-group"><div class="prop-label">'+(lang==='ar'?'المنظور':'Perspective')+'</div><div style="display:flex;gap:3px;flex-wrap:wrap"><button class="angle-btn'+(el.viewMode==='auto'?' on':'')+'" onclick="sp(\'viewMode\',\'auto\')">'+(lang==='ar'?'تلقائي':'Auto')+'</button><button class="angle-btn'+(el.viewMode==='front'?' on':'')+'" onclick="sp(\'viewMode\',\'front\')">'+(lang==='ar'?'أمامي':'Front')+'</button><button class="angle-btn'+(el.viewMode==='back'?' on':'')+'" onclick="sp(\'viewMode\',\'back\')">'+(lang==='ar'?'خلفي':'Back')+'</button><button class="angle-btn'+(el.viewMode==='persp'?' on':'')+'" onclick="sp(\'viewMode\',\'persp\')">'+(lang==='ar'?'عميق':'Depth')+'</button><button class="angle-btn'+(el.viewMode==='top'?' on':'')+'" onclick="sp(\'viewMode\',\'top\')">'+(lang==='ar'?'علوي':'Top')+'</button></div></div>';}
h+='<div class="spotlight-toggle'+(el.spotlight?' active':'')+'" onclick="sp(\'spotlight\','+(!el.spotlight)+')"><i class="fas fa-lightbulb"></i><span>'+t('spotlight')+'</span></div>';
if(el.spotlight){h+='<div style="display:flex;gap:4px;margin-top:4px"><label style="font-size:9px;color:var(--text3)">'+(lang==='ar'?'\u0644\u0648\u0646':'Color')+':</label><input type="color" value="'+(el.spotlightColor||'#ffe864')+'" onchange="sp(\'spotlightColor\',this.value)" style="width:28px;height:22px;border:none;cursor:pointer"><label style="font-size:9px;color:var(--text3)">'+(lang==='ar'?'\u062d\u062c\u0645':'Size')+':</label><input type="range" min="5" max="30" value="'+(Math.round((el.spotlightSize||1)*10))+'" style="flex:1" oninput="sp(\'spotlightSize\',this.value/10)"></div>';}
if(isP)h+='<div class="poszone-toggle'+(el.poszone?' active':'')+'" onclick="sp(\'poszone\','+(!el.poszone)+')"><i class="fas fa-bullseye"></i><span>'+t('poszone')+'</span></div>';
if(el.poszone&&isP){h+='<div style="display:flex;gap:4px;align-items:center;margin-top:4px"><label style="font-size:9px;color:var(--text3)">'+(lang==='ar'?'\u0644\u0648\u0646':'Color')+':</label><input type="color" value="'+(el.poszoneColor||el.color||'#4a90d9')+'" onchange="sp(\'poszoneColor\',this.value)" style="width:28px;height:22px;border:none;cursor:pointer"><label style="font-size:9px;color:var(--text3)">'+(lang==='ar'?'\u0639\u062f\u062f':'Count')+':</label><input type="range" min="1" max="5" value="'+(el.poszoneCount||1)+'" style="width:60px" oninput="sp(\'poszoneCount\',+this.value)"></div>';}
// Connection lines for this player
var myLinks=playerLinks.filter(function(lk){return lk.fromId===el.id||lk.toId===el.id;});
if(myLinks.length>0){h+='<div style="margin-top:6px;border-top:1px solid var(--border);padding-top:6px"><div style="font-size:9px;font-weight:700;color:var(--text3);margin-bottom:4px">'+(lang==='ar'?'\u062e\u0637\u0648\u0637 \u0627\u0644\u0631\u0628\u0637':'Connection Lines')+'</div>';myLinks.forEach(function(lk,idx){h+='<div style="display:flex;gap:4px;align-items:center;margin-bottom:3px"><input type="color" value="'+(lk.color||'#ffffff')+'" onchange="playerLinks['+playerLinks.indexOf(lk)+'].color=this.value;reqRender()" style="width:24px;height:20px;border:none;cursor:pointer"><input type="range" min="1" max="8" value="'+(lk.size||3)+'" onchange="playerLinks['+playerLinks.indexOf(lk)+'].size=+this.value;reqRender()" style="flex:1"><button class="la-btn" onclick="playerLinks.splice('+playerLinks.indexOf(lk)+',1);saveH();updateProps();reqRender()" title="'+t('delete')+'"><i class="fas fa-times" style="color:var(--danger)"></i></button></div>';});h+='</div>';}
if(el.type==='ball'){var linked=els.find(function(e2){return e2.linkedToId===el.id;});if(!linked)h+='<button class="hbtn" style="margin-top:6px;width:100%;font-size:10px" onclick="linkBallSel()"><i class="fas fa-link"></i> '+t('linked')+'</button>';else h+='<button class="hbtn danger" style="margin-top:6px;width:100%;font-size:10px" onclick="unlinkBall('+el.id+')"><i class="fas fa-unlink"></i> '+t('unlink')+'</button>';}

pc.innerHTML=h;
if(el.type==='text'||el.type==='number'){var _tc=document.getElementById('_txtCont');if(_tc)_tc.value=el.text||'';}
if(isP){
  var _pn=document.getElementById('_pnName');if(_pn)_pn.value=el.playerName||'';

}
if(_focId){var _ri=document.getElementById(_focId);if(_ri){_ri.focus();try{_ri.setSelectionRange(_focSS,_focSE);}catch(e){}}}}
function sp(prop,val){if(prop==='playerName'&&val)showPlayerNames=true;selIds.forEach(function(id){var el=els.find(function(e){return e.id===id;});if(el){el[prop]=val;
if(prop==='color'||prop==='size'||prop==='displayStyle'){
var cat=el.type.startsWith('gk')?'goalkeeper':isP2D(el.type)?'player':isZone(el.type)?'zone':el.type;
if(lastElProps[cat]){if(prop==='color')lastElProps[cat].color=val;if(prop==='size')lastElProps[cat].size=val;if(prop==='displayStyle')lastElProps[cat].displayStyle=val;}
}
}});reqRender();if(prop==='spotlight'||prop==='poszone')updateProps();
// Sync formation props if any formation player is selected
selIds.forEach(function(id){var el=els.find(function(e){return e.id===id;});if(el&&el._formationTeam){var team=el._formationTeam;var allTeam=els.filter(function(e2){return e2._formationTeam===team;});if(allTeam.length>0){var s=allTeam[0];var fp=allTeam.find(function(e2){return e2.type!=='gk_stand';});var gp=allTeam.find(function(e2){return e2.type==='gk_stand';});teamFormationProps[team]={size:s.size,displayStyle:s.displayStyle,opacity:s.opacity,jerseyColor2:s.jerseyColor2,spotlight:s.spotlight,poszone:s.poszone,fieldColor:fp?fp.color:s.color,gkColor:gp?gp.color:s.color};}}});}
function deleteSel(){selIds.forEach(function(id){playerLinks=playerLinks.filter(function(lk){return lk.fromId!==id&&lk.toId!==id;});var i=els.findIndex(function(e){return e.id===id;});if(i>=0)els.splice(i,1);});selIds.clear();saveH();updateProps();updateLayers();reqRender();}
function clearAll(){
  showConfirmModal(t('clear'),t('clear_confirm'),function(ok){if(!ok)return;
  els=[];selIds.clear();nCnt=1;grpCnt=1;playerLinks=[];
  teamFormations={A:null,B:null};teamFormationProps={A:null,B:null};
  teamRosterAssignment={A:null,B:null};
  if(typeof trails!=='undefined')trails={};
  saveH();updateProps();updateLayers();renderFormationsPanel();reqRender();
  if(typeof renderRosterList==='function')renderRosterList();
  toast(t('cleared'));
  });
}
// selectAllEls moved to js/engine/SelectionSystem.js
function linkBallSel(){var ball=null;selIds.forEach(function(id){var e=els.find(function(e2){return e2.id===id;});if(e&&e.type==='ball')ball=e;});if(!ball){for(var i=0;i<els.length;i++){if(els[i].type==='ball'&&!els[i].linkedToId){ball=els[i];break;}}}if(!ball)return;var pid=null;selIds.forEach(function(id){if(id!==ball.id)pid=id;});if(pid)linkBallToPlayer(pid,ball.id);}
function updateLayers(){var lp=document.getElementById('layersPanel');if(!lp)return;var h='',_nm=[];for(var i=els.length-1;i>=0;i--){var el=els[i],nm=elName(el),sel=selIds.has(el.id);_nm.push(nm);h+='<div class="layer-item'+(sel?' sel':'')+'" onclick="selLayer(\''+el.id+'\',event)"><div class="layer-icon" style="background:'+el.color+'20;color:'+el.color+'"><i class="fas fa-'+(isP2D(el.type)?'user':el.type==='ball'?'circle':'cube')+'"></i></div><span class="layer-name"></span><div class="layer-actions"><button class="la-btn'+(el.hidden?' vis-off':'')+'" onclick="togVis(\''+el.id+'\',event)" title="Visibility"><i class="fas fa-'+(el.hidden?'eye-slash':'eye')+'"></i></button><button class="la-btn" onclick="togLock(\''+el.id+'\',event)" title="Lock"><i class="fas fa-'+(el.locked?'lock':'lock-open')+'"></i></button><button class="la-btn" onclick="moveLayer(\''+el.id+'\','+'-1,event)" title="Up"><i class="fas fa-chevron-up"></i></button><button class="la-btn" onclick="moveLayer(\''+el.id+'\','+'1,event)" title="Down"><i class="fas fa-chevron-down"></i></button></div></div>';}
if(!els.length)h='<div style="text-align:center;padding:12px;color:var(--text3);font-size:11px"><i class="fas fa-layer-group" style="font-size:16px;opacity:0.3;display:block;margin-bottom:4px"></i><span id="_noElMsg"></span></div>';lp.innerHTML=h;var _ns=lp.querySelectorAll('.layer-name');for(var _j=0;_j<_ns.length&&_j<_nm.length;_j++){_ns[_j].textContent=_nm[_j];}if(!els.length){var _nem=document.getElementById('_noElMsg');if(_nem)_nem.textContent=t('no_elements');}}
function selLayer(id,e){e.stopPropagation();if(e.shiftKey)selIds.has(id)?selIds.delete(id):selIds.add(id);else{selIds.clear();selIds.add(id);}updateProps();updateLayers();reqRender();}
function togVis(id,e){e.stopPropagation();var el=els.find(function(e2){return e2.id===id;});if(el){el.hidden=!el.hidden;updateLayers();reqRender();}}
function togLock(id,e){e.stopPropagation();var el=els.find(function(e2){return e2.id===id;});if(el){el.locked=!el.locked;updateLayers();}}
function moveLayer(id,dir,e){e.stopPropagation();var idx=els.findIndex(function(el){return el.id===id;});var ni=idx+dir;if(ni<0||ni>=els.length)return;var tmp=els[idx];els[idx]=els[ni];els[ni]=tmp;updateLayers();reqRender();}